export { default as Home } from "./Home.svg";
export { default as Ngos } from "./Ngos.svg";
export { default as Cases } from "./Cases.svg";
export { default as Donors } from "./Blood donors.svg";
export { default as Volunteer } from "./Volunteer.svg";
export { default as Notification } from "./Notifcation.svg";
export { default as messages } from "./messages.svg";
export { default as logout } from "./logout.svg";
export { default as search } from "./search.svg";
export { default as APositive } from "./A positive.svg";
export { default as BPositive } from "./B Positive.svg";
export { default as OPositive } from "./O Positive.svg";
export { default as ABPositive } from "./ABpositive.svg";
export { default as ANegative } from "./A Negative.svg";
export { default as BNegative } from "./B Negative.svg";
export { default as ONegative } from "./O negative.svg";
export { default as ABNegative } from "./AB negative.svg";
export { default as donors } from "./donors.svg";
export { default as volunters } from "./volunters.svg";
export { default as case } from "./case.svg";
export { default as ngo } from "./ngo.svg";
